"""
Django settings for solstice project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "a_default_fallback_secret_key_if_not_set")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS_STRING = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1")
ALLOWED_HOSTS = [
    host.strip() for host in ALLOWED_HOSTS_STRING.split(",") if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.video_processing.apps.VideoProcessingConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "solstice.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "solstice.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.getenv("DB_NAME", BASE_DIR / "db.sqlite3"),
        "USER": os.getenv(
            "DB_USER"
        ),  # No default, should be set in .env for PostgreSQL
        "PASSWORD": os.getenv("DB_PASSWORD"),  # No default
        "HOST": os.getenv(
            "DB_HOST"
        ),  # No default for PostgreSQL, 'localhost' or service name
        "PORT": os.getenv("DB_PORT"),  # No default for PostgreSQL, typically '5432'
    }
}

# If using SQLite (the default if DB_ENGINE is not set or is sqlite3),
# and DB_NAME is the default (BASE_DIR / 'db.sqlite3'), ensure NAME is a Path object.
if DATABASES["default"]["ENGINE"] == "django.db.backends.sqlite3" and DATABASES[
    "default"
]["NAME"] == str(BASE_DIR / "db.sqlite3"):
    DATABASES["default"]["NAME"] = BASE_DIR / "db.sqlite3"
elif DATABASES["default"]["ENGINE"] == "django.db.backends.postgresql":
    # Ensure port is an integer if provided
    if DATABASES["default"].get("PORT"):
        try:
            DATABASES["default"]["PORT"] = int(DATABASES["default"]["PORT"])
        except ValueError:
            # Handle error or remove port if invalid, or let Django raise an error
            pass


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS settings
INSTALLED_APPS += ["corsheaders"]

MIDDLEWARE.insert(0, "corsheaders.middleware.CorsMiddleware")

CORS_ALLOW_ALL_ORIGINS = True

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
os.makedirs(MEDIA_ROOT, exist_ok=True)

MEDIA_SUBDIRECTORIES = [
    "ingest/videos",
    "artifacts/pose_estimations",
    "artifacts/normalized_pose_estimations",
    "deliverables/videos",
    "deliverables/thumbnails",
    "temp",
    "logs",
]
for sub in MEDIA_SUBDIRECTORIES:
    os.makedirs(os.path.join(MEDIA_ROOT, sub), exist_ok=True)

DEFAULT_FILE_STORAGE = "apps.video_processing.storage.LocalMediaStorage"

# CELERY SETTINGS

CELERY_BROKER_REDIS_DB_NUMBER = os.getenv("CELERY_BROKER_REDIS_DB_NUMBER", "0")
CELERY_RESULTS_REDIS_DB_NUMBER = os.getenv("CELERY_RESULTS_REDIS_DB_NUMBER", "1")
REDIS_HOST = os.getenv("REDIS_HOST", "localhost")
REDIS_PORT = os.getenv("REDIS_PORT", "6379")

CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/{CELERY_BROKER_REDIS_DB_NUMBER}"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"  # Or your project's timezone
CELERY_RESULT_BACKEND = (
    f"redis://{REDIS_HOST}:{REDIS_PORT}/{CELERY_RESULTS_REDIS_DB_NUMBER}"
)
CELERY_TASK_TRACK_STARTED = True  # So tasks get a 'STARTED' state

MEDIAPIPE_MODELS_BASE_PATH = os.getenv(
    "MEDIAPIPE_MODELS_BASE_PATH", "apps/video_processing/models"
)
