# Generated by Django 5.2.1 on 2025-06-22 14:29

import apps.video_processing.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_processing", "0003_remove_videojob_output_video_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videojob",
            name="norm_pose_data_file",
            field=models.FileField(
                blank=True,
                help_text="Intermediate pose data CSV file generated by the first job stage.",
                null=True,
                upload_to=apps.video_processing.models.get_norm_pose_data_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="videojob",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Upload"),
                    ("UPLOADED", "Uploaded, Awaiting Pose Extraction"),
                    ("POSE_EXTRACTION_QUEUED", "Pose Extraction Queued"),
                    ("EXTRACTING_POSE", "Extracting Pose Data"),
                    (
                        "POSE_DATA_GENERATED",
                        "Pose Data Generated, Awaiting Armature Video",
                    ),
                    ("NORMALISING_POSE_DATA", "Normalising Pose Data"),
                    ("POSE_DATA_NORMALISED", "Pose Data Normalised"),
                    ("ARMATURE_VIDEO_QUEUED", "Armature Video Queued"),
                    ("GENERATING_ARMATURE_VIDEO", "Generating Armature Video"),
                    ("COMPLETED", "Processing Completed"),
                    ("FAILED", "Processing Failed"),
                    ("CLEANED_UP", "Output Cleaned Up"),
                ],
                default="PENDING",
                help_text="Current status of the processing job.",
                max_length=30,
            ),
        ),
    ]
